<a href="https://colab.research.google.com/github/hemangikariya/ML-Lab-Assignments/blob/main/Toyota_Data_Analysis_and_Missing_Values/Dataset_load_and_statastics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using Pandas and NumPy for Data Summarization**

# Step 1: Import Pandas and Load Your Data

In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
# Import pandas and numpy
import pandas as pd
import numpy as np

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Toyota.csv')
df

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [9]:
# Check no. of cell in Dataset
df.size

15796

In [10]:
# Check rows, columns in dataset
df.shape

(1436, 11)

In [11]:
#check data types in DataFrame
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [12]:
df.dtypes.value_counts()

int64      5
object     4
float64    2
Name: count, dtype: int64

In [13]:
# Get the column names of the DF
df.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

# Step 2(A): View the First Few Rows of Your Dataset

In [14]:
# Display the first few rows of the DataFrame
df.head()           # first 5 rows
# df.head(3)          # first 3 rows

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170

# Step 2(B): View the last Few Rows of Your Dataset

In [16]:
# Display the last few rows of the DataFrame
#df.tail()            # Last 5 records
df.tail(3)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
1433,1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

# Step 2(C): View some Few Rows of Your Dataset

In [ ]:
df.sample(5)

# Step 3: Summary Statistics

In [17]:
# info -> Gives info about your dataset
# it gives all column name with its datatype.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1436 non-null   int64
 1   Price       1436 non-null   int64
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object
 4   FuelType    1336 non-null   object
 5   HP          1436 non-null   object
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64
 8   CC          1436 non-null   int64
 9   Doors       1436 non-null   object
 10  Weight      1436 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB

In [18]:
# Summary statistics for numerical columns
df.describe()

,Unnamed: 0,Price,Age,MetColor,Automatic,CC,Weight
count,1436.000000,1436.000000,1336.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,717.500000,10730.824513,55.672156,0.674961,0.055710,1566.827994,1072.45961
std,414.681806,3626.964585,18.589804,0.468572,0.229441,187.182436,52.64112
min,0.000000,4350.000000,1.000000,0.000000,0.000000,1300.000000,1000.00000
25%,358.750000,8450.000000,43.000000,0.000000,0.000000,1400.000000,1040.00000
50%,717.500000,9900.000000,60.000000,1.000000,0.000000,1600.000000,1070.00000
75%,1076.250000,11950.000000,70.000000,1.000000,0.000000,1600.000000,1085.00000
max,1435.000000,32500.000000,80.000000,1.000000,1.000000,2000.000000,1615.00000

# Step 4: Individual Descriptive Statistics

In [19]:
print(f"Mean of weight:: {df['Weight'].mean()}")
print(f"Median of weight:: {df['Weight'].median()}")
print(f"Mode of Metcolor :: {df['MetColor'].mode()}")
print(f"Standard deviation of weight:: {df['Weight'].std()}")

# Calculate percentiles using NumPy
percentile_25 = np.percentile(df['Weight'], 25)
percentile_75 = np.percentile(df['Weight'], 75)
print(f"Percentile at 25% {percentile_25}")
print(f"Percentile at 75% {percentile_75}")

Mean of weight:: 1072.4596100278552
Median of weight:: 1070.0
Mode of Metcolor :: 0    1.0
Name: MetColor, dtype: float64
Standard deviation of weight:: 52.6411204869316
Percentile at 25% 1040.0
Percentile at 75% 1085.0

In [20]:
# isnull -> Gives you how many null values are there in each column

df.isnull()

# False means not null
# True means null

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1431,False,False,True,False,False,False,False,False,False,False,False
1432,False,False,False,False,False,False,False,False,False,False,False
1433,False,False,True,False,False,False,False,False,False,False,False
1434,False,False,False,False,True,False,False,False,False,False,False
1435,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [22]:
# duplicated ->  It gives how many duplicate data are in dataset
df.duplicated()

# so, here false means no duplicate

0       False
1       False
2       False
3       False
4       False
        ...
1431    False
1432    False
1433    False
1434    False
1435    False
Length: 1436, dtype: bool

In [23]:
# let take sum of it and check is there any duplicate rows are there in dataset
int(df.duplicated().sum())

# So ans wer is 0 means no duplicate row

0