<a href="https://colab.research.google.com/github/hemangikariya/ML-Lab-Assignments/blob/main/Toyota_Data_Analysis_and_Missing_Values/3_Two_way_cross_tabulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Toyota.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,7500,NaN,20544,Petrol,86,1.0,0,1300,3,1025
1432,1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1433,1433,8500,NaN,17016,Petrol,86,0.0,0,1300,3,1015
1434,1434,7250,70.0,??,NaN,86,1.0,0,1300,3,1015
1435,1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1436 non-null   int64
 1   Price       1436 non-null   int64
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object
 4   FuelType    1336 non-null   object
 5   HP          1436 non-null   object
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64
 8   CC          1436 non-null   int64
 9   Doors       1436 non-null   object
 10  Weight      1436 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB

In [ ]:
df.shape

(1436, 11)

In [ ]:
df['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [ ]:
df.dropna()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
5,5,12950,32.0,61000,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...,...
1425,1425,7950,80.0,??,Petrol,86,1.0,0,1300,4,1000
1429,1429,8950,78.0,24000,Petrol,86,1.0,1,1300,5,1065
1430,1430,8450,80.0,23000,Petrol,86,0.0,0,1300,3,1015
1432,1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1435,1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

# Data Cleaning
# Drop some rows having NA values

In [ ]:
# index_col = 0 make first column as index
# na_values Replace the values given in list as NA
cars_df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toyota.csv",index_col=0,na_values=['??','????'])
cars_df.info()
cars_df.dropna(inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object
 4   HP         1430 non-null   float64
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64
 7   CC         1436 non-null   int64
 8   Doors      1436 non-null   object
 9   Weight     1436 non-null   int64
dtypes: float64(4), int64(4), object(2)
memory usage: 123.4+ KB

# Change values of Doors (Three=3, Four=4, Five=5)

In [ ]:
cars_df['Doors'].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [ ]:
# cleaning column 'Doors'
cars_df.replace({'three':3},inplace=True)
#cars_df['Doors'].replace('three',3,inplace=True)
cars_df['Doors'].replace('four',4,inplace=True)
cars_df['Doors'].replace('five',5,inplace=True)

/tmp/ipykernel_1211/1140449207.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_df['Doors'].replace('four',4,inplace=True)
/tmp/ipykernel_1211/1140449207.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_df['Doors'].replace('five',5,inplace=True)

In [ ]:
cars_df['Doors'].unique()

array([3, '3', '5', '4', 4, 5, '2'], dtype=object)

In [ ]:
cars_df['Doors']=cars_df['Doors'].astype('int64')
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1096 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1096 non-null   int64
 1   Age        1096 non-null   float64
 2   KM         1096 non-null   float64
 3   FuelType   1096 non-null   object
 4   HP         1096 non-null   float64
 5   MetColor   1096 non-null   float64
 6   Automatic  1096 non-null   int64
 7   CC         1096 non-null   int64
 8   Doors      1096 non-null   int64
 9   Weight     1096 non-null   int64
dtypes: float64(4), int64(5), object(1)
memory usage: 94.2+ KB

# Two-way cross Tabulation
# A two-way cross-tabulation summarizes the association between two categorical (i.e., nominal, ordinal) variables.

In [ ]:
cars_df['FuelType'].value_counts()

FuelType
Petrol    968
Diesel    116
CNG        12
Name: count, dtype: int64

In [ ]:
pd.crosstab(index=cars_df['FuelType'],columns='count')

col_0     count
FuelType
CNG          12
Diesel      116
Petrol      968

In [ ]:
pd.crosstab(index=cars_df['Automatic'],columns=cars_df['FuelType'],dropna=True)

FuelType   CNG  Diesel  Petrol
Automatic
0           12     116     910
1            0       0      58

In [ ]:
pd.crosstab(index=cars_df['MetColor'],columns=cars_df['FuelType'],dropna=True)

FuelType  CNG  Diesel  Petrol
MetColor
0.0         4      43     311
1.0         8      73     657

In [ ]:
pd.crosstab(index=cars_df['Doors'],columns=cars_df['FuelType'],dropna=True)

FuelType  CNG  Diesel  Petrol
Doors
2           0       1       1
3           5      42     416
4           0      10      86
5           7      63     465